name: reusable_dev_external

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  dev_external:
    uses: ./.github/workflows/reusable_build.yml
    with:
      env: ${{ inputs.env }}
